---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesJson6902:
  - target:
      version: v1beta1
      kind: AutomationController
      name: controller
      namespace: ansible-automation-platform
    path: nameupdate.yaml
