apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: rhbk-sso
  namespace: rhbk-sso
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres-db
    usernameSecret:
      name: postgres-db-secret
      key: username
    passwordSecret:
      name: postgres-db-secret
      key: password
  http:
    tlsSecret: $CERTSECRET
  hostname:
    hostname: keycloak.apps.dd-aro.eastus.aroapp.io